DROP TABLE emp;

CREATE TABLE emp(
  id NUMBER,
  name VARCHAR2(100)
);

DROP TABLE which_fired_first;

CREATE TABLE which_fired_first (
  seq NUMBER,
  trigger_name VARCHAR2(100)
);

DROP SEQUENCE s1;

CREATE SEQUENCE s1;

CREATE OR REPLACE TRIGGER t1 BEFORE INSERT ON emp 
BEGIN
  INSERT INTO which_fired_first VALUES(s1.NEXTVAL, 't1');
END;


CREATE OR REPLACE TRIGGER t2 BEFORE INSERT ON emp 
BEGIN
  INSERT INTO which_fired_first VALUES(s1.NEXTVAL, 't2');
END;

INSERT INTO emp VALUES(2, 'Juan');

SELECT *
FROM WHICH_FIRED_FIRST;

CREATE OR REPLACE TRIGGER t2 BEFORE INSERT ON emp FOLLOWS t1
BEGIN
  INSERT INTO which_fired_first VALUES(s1.NEXTVAL, 't2');
END;

