ALTER SESSION SET CONTAINER=orclpdb;

SHOW con_name;

DROP TABLE log_table;

CREATE TABLE log_table(
  user_id VARCHAR2(100),
  log_date DATE,
  action VARCHAR2(100)
);

CREATE OR REPLACE TRIGGER logon_t AFTER LOGON ON DATABASE 
BEGIN
  INSERT INTO log_table VALUES(USER, SYSDATE, 'logon');
END;

CREATE OR REPLACE TRIGGER logoff_t BEFORE LOGOFF ON DATABASE
BEGIN
  INSERT INTO log_table VALUES(USER, SYSDATE, 'logoff');
END;

SELECT *
FROM LOG_TABLE;

DROP TRIGGER logon_t;
DROP TRIGGER logoff_t;