DROP TABLE test_emp;

CREATE TABLE test_emp(
  emp_id NUMBER,
  first_name VARCHAR2(100)
);

CREATE OR REPLACE TRIGGER comp_test FOR INSERT OR UPDATE OR DELETE ON test_emp
COMPOUND TRIGGER
  BEFORE STATEMENT IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('1');
  END BEFORE STATEMENT;
  
  BEFORE EACH ROW IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('2');
  END BEFORE EACH ROW;
  
  AFTER EACH ROW IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('3');
  END AFTER EACH ROW;
  
  AFTER STATEMENT IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('4');
  END AFTER STATEMENT;
END;

INSERT INTO test_emp
VALUES (1, 'mazen');

INSERT INTO test_emp
SELECT employee_id, first_name
FROM employees
WHERE department_id=20;