DROP TABLE STUDENTS;

CREATE TABLE STUDENTS (
STUDENT_ID NUMBER,
STUDENT_NAME VARCHAR2(100),
DOB DATE
);

INSERT INTO STUDENTS(STUDENT_ID, STUDENT_NAME, DOB) VALUES (1, 'Juan Vivas', TO_DATE('01011990', 'DDMMYYYY'));
INSERT INTO STUDENTS(STUDENT_ID, STUDENT_NAME, DOB) VALUES (2, 'Ana Vivas', TO_DATE('01011989', 'DDMMYYYY'));
INSERT INTO STUDENTS(STUDENT_ID, STUDENT_NAME, DOB) VALUES (3, 'Luis Vivas', TO_DATE('01011970', 'DDMMYYYY'));
INSERT INTO STUDENTS(STUDENT_ID, STUDENT_NAME, DOB) VALUES (4, 'Juana de Vivas', TO_DATE('01011975', 'DDMMYYYY'));

COMMIT;

SELECT * FROM STUDENTS;

CREATE OR REPLACE VIEW v1_students AS
  SELECT * FROM STUDENTS;
  
CREATE OR REPLACE VIEW V2_STUDENTS AS
  SELECT STUDENT_ID, DOB FROM STUDENTS;
  
CREATE OR REPLACE PROCEDURE PRINT_ALL_STUDENTS IS
BEGIN
  FOR I IN (SELECT * FROM STUDENTS) LOOP
    DBMS_OUTPUT.PUT_LINE(I.STUDENT_ID||' '||I.STUDENT_NAME);
  END LOOP;
END;

SELECT *
FROM USER_DEPENDENCIES
WHERE REFERENCED_NAME='STUDENTS';

CREATE OR REPLACE PROCEDURE PRINT_ALL_STUDENTS_FROM_V1 IS
BEGIN
  FOR I IN (SELECT * FROM V1_STUDENTS) LOOP
    DBMS_OUTPUT.PUT_LINE(I.STUDENT_ID);
  END LOOP;
END;

SELECT *
FROM USER_DEPENDENCIES
WHERE REFERENCED_NAME='STUDENTS';

@/home/oracle/Documents/utldtree.sql

SELECT *
FROM USER_OBJECTS
WHERE LOWER(OBJECT_NAME) LIKE '%tree%';

EXEC DEPTREE_FILL('TABLE', 'HR', 'STUDENTS');

SELECT *
FROM DEPTREE
ORDER BY SEQ#;

CREATE OR REPLACE PROCEDURE TRT IS
BEGIN
  PRINT_ALL_STUDENTS_FROM_V1;
END;


EXEC DEPTREE_FILL('TABLE', 'HR', 'STUDENTS');

SELECT *
FROM DEPTREE
ORDER BY SEQ#;